version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.13
  pre_build:
    commands:
      - mkdir -p $GOPATH/src/github.com/aws/amazon-ecs-cli
      - cp -R . $GOPATH/src/github.com/aws/amazon-ecs-cli/
      - cd $GOPATH/src/github.com/aws/amazon-ecs-cli/
  build:
    commands:
      - make integ-test
      - ./bin/local/ecs-cli.test
